db.zen.insertMany([
    {
        "user" : "joel",
        "codekata" : 235,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-10>"),
        "tasks" : "movie_app",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },
    {
        "user" : "anand",
        "codekata" : 200,
        "attendance" : "Present",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-16>"),
        "tasks" : "mongo_commands",
        "company_drives" : "TCS",
        "company_drives_date" : new Date("<2020-10-25>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },    
    {
        "user" : "imran",
        "codekata" : 175,
        "attendance" : "Present",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-21>"),
        "tasks" : "create_api",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },
    {
        "user" : "malini",
        "codekata" : 150,
        "attendance" : "Present",
        "topics" : "HTML",
        "topic_date" : new Date("<2020-10-07>"),
        "task_date" : new Date("<2020-10-09>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Appeared",
        "mentors" : "bala"
    },    
    {
        "user" : "Ram",
        "codekata" : 250,
        "attendance" : "Present",
        "topics" : "CSS",
        "topic_date" : new Date("<2020-10-12>"),
        "task_date" : new Date("<2020-10-14>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "bala"
    }, 
    {
        "user" : "Anbu",
        "codekata" : 93,
        "attendance" : "Absent",
        "topics" : "JavaScript",
        "topic_date" : new Date("<2020-10-19>"),
        "task_date" : new Date("<2020-10-23>"),
        "tasks" : "functions",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Not_appeared",
        "mentors" : "basir"
    },    
    {
        "user" : "Dim",
        "codekata" : 180,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-16>"),
        "tasks" : "movie_app",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },
    {
        "user" : "jai",
        "codekata" : 125,
        "attendance" : "Present",
        "topics" : "CSS",
        "topic_date" : new Date("<2020-10-12>"),
        "task_date" : new Date("<2020-10-20>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "TCS",
        "company_drives_date" : new Date("<2020-10-25>"),
        "placement": "Appeared",
        "mentors" : "bala"
    },    
    {
        "user" : "balan",
        "codekata" : 155,
        "attendance" : "Present",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-21>"),
        "tasks" : "create_api",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },
    {
        "user" : "priya",
        "codekata" : 55,
        "attendance" : "Present",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-19>"),
        "tasks" : "mongo_commands",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },    
    {
        "user" : "sachin",
        "codekata" : 68,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-16>"),
        "tasks" : "movie_app",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Not_appeared",
        "mentors" : "mani"
    }, 
    {
        "user" : "dravid",
        "codekata" : 250,
        "attendance" : "Absent",
        "topics" : "JavaScript",
        "topic_date" : new Date("<2020-10-19>"),
        "task_date" : new Date("<2020-10-23>"),
        "tasks" : "functions",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "basir"
    },    {
        "user" : "ismail",
        "codekata" : 95,
        "attendance" : "Present",
        "topics" : "HTML",
        "topic_date" : new Date("<2020-10-07>"),
        "task_date" : new Date("<2020-10-09>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Not_appeared",
        "mentors" : "bala"
    },
    {
        "user" : "swarna",
        "codekata" : 200,
        "attendance" : "Present",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-25>"),
        "tasks" : "create_api",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },    
    {
        "user" : "srimathi",
        "codekata" : 175,
        "attendance" : "Present",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-20>"),
        "tasks" : "mongo_commands",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },
    {
        "user" : "binditha",
        "codekata" : 105,
        "attendance" : "Absent",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-22>"),
        "tasks" : "movie_app",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },    
    {
        "user" : "alwin",
        "codekata" : 265,
        "attendance" : "Present",
        "topics" : "HTML",
        "topic_date" : new Date("<2020-10-07>"),
        "task_date" : new Date("<2020-10-11>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Appeared",
        "mentors" : "bala"
    }, 
    {
        "user" : "srima",
        "codekata" : 300,
        "attendance" : "Present",
        "topics" : "JavaScript",
        "topic_date" : new Date("<2020-10-19>"),
        "task_date" : new Date("<2020-10-29>"),
        "tasks" : "functions",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "imran"
    },    {
        "user" : "yogesh",
        "codekata" : 30,
        "attendance" : "Absent",
        "topics" : "CSS",
        "topic_date" : new Date("<2020-10-12>"),
        "task_date" : new Date("<2020-10-16>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "bala"
    },
    {
        "user" : "Sai",
        "codekata" : 177,
        "attendance" : "Present",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-17>"),
        "tasks" : "mongo_commands",
        "company_drives" : "TCS",
        "company_drives_date" : new Date("<2020-10-25>"),
        "placement": "Not_appeared",
        "mentors" : "mani"
    },    
    {
        "user" : "rabort",
        "codekata" : 133,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-11>"),
        "tasks" : "movie_app",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },
    {
        "user" : "princy",
        "codekata" : 222,
        "attendance" : "Absent",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-22>"),
        "tasks" : "create_api",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },    
    {
        "user" : "nivi",
        "codekata" : 50,
        "attendance" : "Absent",
        "topics" : "HTML",
        "topic_date" : new Date("<2020-10-07>"),
        "task_date" : new Date("<2020-10-09>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "bala"
    }, 
    {
        "user" : "Ishu",
        "codekata" : 350,
        "attendance" : "Present",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-25>"),
        "tasks" : "create_api",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "mani"
    },
    {
        "user" : "zaheer",
        "codekata" : 88,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-15>"),
        "tasks" : "movie_app",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Not_appeared",
        "mentors" : "mani"
    },
    {
        "user" : "sudha",
        "codekata" : 189,
        "attendance" : "Present",
        "topics" : "JavaScript",
        "topic_date" : new Date("<2020-10-19>"),
        "task_date" : new Date("<2020-10-25>"),
        "tasks" : "functions",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "basir"
    },
    {
        "user" : "srimu",
        "codekata" : 159,
        "attendance" : "Absent",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-21>"),
        "tasks" : "mongo_commands",
        "company_drives" : "TCS",
        "company_drives_date" : new Date("<2020-10-25>"),
        "placement": "Appeared",
        "mentors" : "imran"
    },
]);